version: 2.1

workflows:
  test-dast:
    jobs:
      - scan
jobs:
  scan:
    docker:
      - image: zaproxy/zap-stable
    steps:
      - run:
            command: |
              mkdir /zap/wrk
              zap-baseline.py -t http://172.27.151.110:8085/hospital/index.php -r report.html              
      - store_artifacts:
          path: /zap/wrk
          destination: zap-report
